name: Modifications Flow
on:
  push:
    branches:
      - chore/modifications
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            keep-outputs = true
            keep-derivations = true
      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/mikearnaldi/kube-ovn
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Kube-OVN
        run: make build-go
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ./dist/images
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}